[project]
name = "icici_collection"
version = "0.0.1"
description = "Get response and set payment entry"
authors = [
  { name = "Erpdata", email = "contact@erpdata.in" }
]
requires-python = ">=3.10"
readme = "README.md"
dependencies = [
  "qrcode[pil]",
  "bs4",
  "pycryptodome",
  "wheel",
  "pandas",
  "openpyxl"
]

[tool.frappe]
app_name = "icici_collection"

[tool.bench.frappe-dependencies]
frappe = ">=16.0.0,<17.0.0"
